Revert "SQUAD : Adding a memory footprint gathering script launched from ci"
This reverts commit b605c6ce6e5e150e8f0eb7a22286381863955a47.

Reason for revert:
python3 tf-m-ci-scripts/memory_footprint.py /home/buildslave/workspace/tf-m-build-config/trusted-firmware-m/ AN521_GNUARM_PSA_2_Debug_BL2_NS_MEDIUM Default,CoreIPC,CoreIPCTfmLevel2 ****
Traceback (most recent call last):
  File "tf-m-ci-scripts/memory_footprint.py", line 207, in <module>
    config = identify_config(CI_CONFIG)
  File "tf-m-ci-scripts/memory_footprint.py", line 138, in identify_config
    arguments = get_config(CI_CONFIG)
  File "tf-m-ci-scripts/memory_footprint.py", line 115, in get_config
    match_dict = m.groupdict()
AttributeError: 'NoneType' object has no attribute 'groupdict'

Change-Id: I6ad9ae8dc30298ee9622c4438a2a8f84bcf0ce0e